title: Johanna Karras 
logo:  "/images/johanna.jpg?raw=true" 
description: 
  Welcome to my website!
  <br><br>
  I am a first-year PhD student focusing in machine learning and computer vision at the 
  Graphics and Imaging Lab (GRAIL) at UW.
  <br><br>
  <a href="https://www.linkedin.com/in/johannakarras/">My LinkedIn Profile</a> 
  <a href="/files/CV.pdf" download>Download CV</a>
  
theme: jekyll-theme-minimal
google_analytics: G-P1TRDSL2Q1 # your Google Analytics tracking ID here
