title: Johanna Karras 
logo:  "/images/johanna.jpg?raw=true" 
description: 
  Welcome to my website!
  <br><br>
  I am a fourth-year PhD student focusing in generative AI at the 
  Graphics and Imaging Lab (GRAIL) at UW.
  <br><br>
  <a href="https://www.linkedin.com/in/johannakarras/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-208766788-1 # your Google Analytics tracking ID here
