title: Johanna Karras 
logo: "/images/johanna.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Student @ UW
  <br><br>
  Welcome to my website! I am a first-year PhD student focusing in machine learning and computer vision at the 
  Graphics and Imaging Lab (GRAIL) at UW.
  <br><br>
  <a href="https://www.linkedin.com/in/johannakarras/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
